import Head from 'next/head'
import SideBar from '../components/SideBar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Whats app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideBar />
    </div>
  )
}
